#!/bin/sh
#--------------------------------------------------------------------------------+
# BSD 3-Clause License
#
# Copyright (c) 2022,2023 Alonso Cárdenas (acardenas@bsd-peru.org)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

tui_init() {
	local _menu

	_menu=$(${DIALOG_BIN} --nocancel --backtitle "Wireguard administration tool" \
				--title "Wireguard administration tool" \
				--menu "Select one option:" 12 60 5 \
                        1 "Server management" \
                        2 "Groups management" \
                        3 "Clients management" \
                        4 "Exit" \
        3>&1 1>&2 2>&3)

	case ${_menu} in
		1)      tui_server
			;;
		2)      tui_group
			;;
		3)      tui_client
			;;
		4)      echo "Bye"
			exit
			;;
	esac

	tui_init
}

tui_server() {
	local _server_menu

	_server_menu=$(${DIALOG_BIN} --nocancel --backtitle "Wireguard administration tool" \
				--title "Server management" \
				--menu "Select one option:" 12 60 5  \
                        1 "Edit configuration" \
                        2 "Apply configuration" \
                        3 "Backup configuration files" \
                        4 "Exit" \
        3>&1 1>&2 2>&3)

        case ${_server_menu} in
        1)  tui_server_edit
			tui_server
            ;;
		2)	tui_server_apply
			tui_server
			;;
		3)	tui_server_backup
			tui_server
			;;
		4)	tui_init
			;;
        esac
}

tui_server_edit() {
	local _client_output
	local _server_output
	local _server_ip="$1"
	local _server_port="$2"
	local _server_interface="$3"
	local _server_subnet="$4"
	local _server_subnet_ip="$5"
	local _client_allowedips="$6"
	local _client_dns="$7"
	local _check
	local _check_error=0
	local _msgcheck="\n"
	local _continue=0

	if [ -e ${ETCPATH}/wg-shadmin.conf ]; then
	        _server_ip=$(grep "wireguard_server_endpoint=" ${ETCPATH}/wg-shadmin.conf | cut -d '"' -f2)
	        _server_port=$(grep "wireguard_port=" ${ETCPATH}/wg-shadmin.conf | cut -d '"' -f2)
	        _server_interface=$(grep "wireguard_interface=" ${ETCPATH}/wg-shadmin.conf | cut -d '"' -f2)
	        _server_subnet_ip=$(grep "wireguard_interface_ip=" ${ETCPATH}/wg-shadmin.conf | cut -d '"' -f2)
	        _server_subnet=$(grep "wireguard_network=" ${ETCPATH}/wg-shadmin.conf | cut -d '"' -f2)
		_client_allowedips=$(grep "wireguard_allowedips=" ${ETCPATH}/wg-shadmin.conf | cut -d '"' -f2)
		_client_dns=$(grep "wireguard_dns=" ${ETCPATH}/wg-shadmin.conf | cut -d '"' -f2)
	fi

	while true
	do
		_check=0
		_check_error=0

		_server_output=$(${DIALOG_BIN} --ok-label "Next" \
			--cancel-label "Cancel" \
			--backtitle "Wireguard administration tool" \
			--title "Edit configuration" \
			--form "Create a new configuration" 15 60 0 \
				"Server IP/Domain endpoint:" 1 1 "${_server_ip}" 1 28 28 80 \
				"Server port:" 2 1 "${_server_port}" 2 28 6 5 \
				"Server interface:" 3 1 "${_server_interface}" 3 28 5 4 \
				"Server network subnet:" 4 1 "${_server_subnet}" 4 28 19 18 \
				"Server subnet IP:" 5 1 "${_server_subnet_ip}" 5 28 16 15 \
		3>&1 1>&2 2>&3)

		if [ "$?" -eq "0" ]; then
			_server_ip=$(echo "${_server_output}" | sed -n 1p)
			_server_port=$(echo "${_server_output}" | sed -n 2p)
			_server_interface=$(echo "${_server_output}" | sed -n 3p)
			_server_subnet=$(echo "${_server_output}" | sed -n 4p)
			_server_subnet_ip=$(echo "${_server_output}" | sed -n 5p)

			_check=$(util_validate_ip_format "${_server_ip}")

			if [ ${_check} -eq 1 ]; then
				_msgcheck=${_msgcheck}"Server IP \"${_server_ip}\" address is not valid\n\n"
				_check_error=1
			fi

			_check=$(util_validate_ip_format "${_server_subnet_ip}")

			if [ ${_check} -eq 1 ]; then
				_msgcheck=${_msgcheck}"Server subnet IP \"${_server_subnet_ip}\" address is not valid\n\n"
				_check_error=1
			fi

			_check=$(util_check_host "${_server_subnet}" "${_server_subnet_ip}")

			if [ ${_check} -eq 1 ]; then
				_msgcheck=${_msgcheck}"Server subnet IP \"${_server_subnet_ip}\" is not part of subnet \"${_server_subnet}\" \n\n"
				_check_error=1
			fi

			if [ ${_check_error} -eq 1 ]; then
				tui_infobox "Server management - Error" "${_msgcheck}" "4"
			else
				break;
			fi
		else
			return 1
		fi
	done

	while true
	do
		_check_error=0
		_msgcheck="\n"

		_client_output=$(${DIALOG_BIN} --ok-label "Next" \
			--cancel-label "Cancel" \
			--backtitle "Wireguard administration tool" \
			--title "Edit configuration" \
			--form "Client option configuration" 10 60 0 \
				"Client allowed IPs:" 1 1 "${_client_allowedips}" 1 25 25 80 \
				"Client DNS IP:" 2 1 "${_client_dns}" 2 25 25 80 \
		3>&1 1>&2 2>&3)

		if [ "$?" -eq "0" ]; then
			_client_allowedips=$(echo "${_client_output}" | sed -n 1p)
			_client_dns=$(echo "${_client_output}" | sed -n 2p)

			if [ -z ${_client_allowedips} ]; then
				_msgcheck=${_msgcheck}"Allowed IPs must not be empty\n\n"
	                        _check_error=1
			fi

			if [ -z ${_client_dns}]; then
				_msgcheck=${_msgcheck}"DNS must not be empty\n\n"
	                        _check_error=1
			fi

			if [ ${_check_error} -eq 1 ]; then
				tui_infobox "Server management - Error" "${_msgcheck}" "4"
			else
				break;
	        fi

		else
			return 1
		fi
	done

	if [ ${_continue} = 0 ]; then
		server_init_config "${_server_ip}" "${_server_port}" "${_server_interface}" "${_server_subnet}" "${_server_subnet_ip}"
		client_init_config "${_client_allowedips}" "${_client_dns}"

		tui_yesno "Server management" "Do you want generate server public and private keys?"

		if [ "$?" -eq "0" ]; then
			server_init_config_keys
		fi

		tui_infobox "Server management" "Changes were saved" "2"
	fi

	return 0
}

tui_server_apply() {
	server_generate_config "${ETCPATH}/wg-shadmin-clients.conf"

	tui_infobox "Server management" "Server configuration file was generated" "2"

	tui_yesno "Server management" "Do you want apply new server configuration file?"

	if [ "$?" -eq "0" ]; then
		util_apply_config

		tui_infobox "Server management" "Server configuration was applied correctly" "2"

		return 0
	else
		return 1
	fi
}

tui_server_backup() {
	local _date

	_date=$(date "+%Y%m%d%H%M")

	tui_yesno "Server management" "Do you want to backup configuration files?"

	if [ "$?" -eq "0" ]; then
		util_make_backup "${_date}"

		tui_infobox "Server management" "Backup ${_date} was created correctly" "2"
		return 0
	else
		return 1
	fi
}

tui_group() {
	local _group_menu

	_group_menu=$(${DIALOG_BIN} --nocancel --backtitle "Wireguard administration tool" \
                --title "Group management" \
                --menu "Select one option:" 12 60 5 \
                        1 "Add group" \
                        2 "Edit group" \
                        3 "Exit" \
	3>&1 1>&2 2>&3)

	case ${_group_menu} in
		1)	tui_group_add
			tui_group
			;;
		2)	tui_group_edit
			tui_group
			;;
		3)	tui_init
			;;
	esac

	echo ${_group_menu}
}

tui_group_add() {
	local _group_output
	local _n

	_n=$(group_generate_id "${ETCPATH}/wg-shadmin-groups.conf")

	while true
	do
		_group_output=$(${DIALOG_BIN} --title "Add group" --inputbox "Put group-${_n} name:" 10 60 3>&1 1>&2 2>&3)

		if [ "$?" -eq "1" ]; then
			return 1
		fi

		if [ -n "${_group_output}" ]; then
			break;
		else
			tui_infobox "Group management" "Group name can not be empty" "2"
		fi
	done

	tui_yesno "Group management" "Do you want add ${_group_output} group?"

	if [ "$?" -eq "0" ]; then
		group_save "group-${_n}" "${_group_output}"

		tui_infobox "Group management" "New group ${group_output} was saved" "2"

		return 0
	fi
}

tui_group_edit() {
	local _group_file="$1"
	local _group_name
	local _group_desc
	local _group_old_desc
	local _group
	local _group_list=""
	local _group_output
	local _status

	_group_list=$(group_list "${ETCPATH}/wg-shadmin-groups.conf")

	while [ ${_group_list} != "" ];
	do
		_group_output=$(echo ${_group_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
		        --title "Group management" \
			--radiolist "Select one group:" 15 60 10 \
		3>&1 1>&2 2>&3)

		_status=$(util_check_status "$?")

		if [ "${_status}" -eq "1" ]; then
			return 1
		fi

		_group_old_desc=$(util_config_get "${ETCPATH}/wg-shadmin-groups.conf" "${_group_output}")
		_group_desc=$(${DIALOG_BIN} --nocancel --title "Edit group ${_group_output}" --inputbox "Put new group description:" 10 50 "${_group_old_desc}" 3>&1 1>&2 2>&3)

		util_config_set "${ETCPATH}/wg-shadmin-groups.conf" "${_group_output}" "${_group_desc}"

		tui_infobox "Group configuration" "${_group_output} change was saved" "2"
	done

	return 0
}


tui_client() {
	local _client_menu

	_client_menu=$(${DIALOG_BIN} --nocancel --backtitle "Wireguard administration tool" \
                --title "Client management" \
                --menu "Select one option:" 15 60 10 \
                        1 "Add client" \
                        2 "Edit client" \
                        3 "Enable/disable client" \
                        4 "Generate client configuration file" \
                        5 "Generate massive client configuration files" \
                        6 "Generate client qr code" \
                        7 "View clients" \
                        8 "Exit" \

	3>&1 1>&2 2>&3)

	case ${_client_menu} in
		1)  tui_client_add
			tui_client
			;;
		2)	tui_client_edit
			tui_client
			;;
		3)	tui_client_activate
			tui_client
			;;
		4)	tui_client_generate_file
			tui_client
			;;
		5)	tui_client_generate_files
			tui_client
			;;
		6)	tui_client_generate_qrcode
			tui_client
			;;
		7)	tui_client_view
			tui_client
			;;
		8)	tui_init
			;;
	esac

	echo ${_client_menu}
}

tui_client_add() {
	local _client_output=""
	local _client_ip
	local _client_fullname
	local _client_keepalive
	local _client_preshared
	local _client_active
	local _client_group
	local _client_peer_name
	local _server_subnet
	local _group_name
	local _group_desc
	local _group
	local _group_list=""
	local _check=0
	local _n

	_client_ip=$(client_generate_ip "${ETCPATH}/wg-shadmin-clients.conf")

	while [ "${_client_ip}" != "" ];
	do
		_client_ip=$(${DIALOG_BIN} --title "Add client" --inputbox "Put client ip address:" 10 60 "${_client_ip}" 3>&1 1>&2 2>&3)

		if [ "$?" -eq "1" ]; then
			return 1
		fi

                _client_ip=$(util_validate_ip_format "${_client_ip}")
		_server_subnet=$(util_config_get "${ETCPATH}/wg-shadmin.conf" "wireguard_network")
		_check=$(util_config_get_exists "${ETCPATH}/wg-shadmin-clients.conf" "${_client_ip}")

		if [ ${_client_ip} = 1 ] || [ ${_check} -eq 0 ]; then
			tui_infobox "Add client - Error" "IP address is not valid or already is used by another peer" "3"
		else
			_check=$(util_check_host "${_server_subnet}" "${_client_ip}")

			if [ ${_check} -eq 1 ]; then
				tui_infobox "Add client - Error" "Server subnet IP ${_client_ip} is not part of subnet ${_server_subnet} \n\n" "3"
			else
				break;
			fi
		fi
	done

	while true
	do
		_client_fullname=$(${DIALOG_BIN} --title "Add client" --inputbox "Put user full name:" 10 60 3>&1 1>&2 2>&3)

		if [ "$?" -eq "1" ]; then
			return 1
		fi

		if [ -n ${_group_output} ]; then
			break;
		else
			tui_infobox "Add client" "User full name can not be empty" "2"
		fi
	done

	tui_yesno "Add client" "Do you want add Keep Alive option?"

	if [ "$?" -eq "0" ]; then
		_client_keepalive=25
	else
		_client_keepalive=0
	fi

	tui_yesno "Add client" "Do you want generate a preshared key?"

	if [ "$?" -eq "0" ]; then
		_client_preshared=YES
	else
		_client_preshared=NO
	fi

	tui_yesno "Add client" "Do you want activate this peer by default?"

	if [ "$?" -eq "0" ]; then
		_client_active=YES
	else
		_client_active=NO
	fi

	_group_list=$(group_list "${ETCPATH}/wg-shadmin-groups.conf")

	while [ ${_group_list} != "" ];
	do
		_client_group=$(echo ${_group_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
			--title "Add client" \
			--radiolist "Select one group:" 15 60 10 \
		3>&1 1>&2 2>&3)

		if [ -z ${_client_group} ]; then
			tui_infobox "Add client" "You must select a group" "2"
		else
			break;
		fi
	done

	_client_output=$(${DIALOG_BIN} --ok-label "Create" \
		--cancel-label "Cancel" \
		--backtitle "Wireguard administration tool" \
		--title "Add client" \
		--mixedform "Create a new configuration" 15 60 0 \
			"Client IP:" 1 1 "${_client_ip}" 1 25 16 15 2 \
			"Client active:" 2 1 "${_client_active}" 2 25 5 4 2 \
			"Client fullname:" 3 1 "${_client_fullname}" 3 25 23 22 0 \
			"Client keepalive:" 4 1 "${_client_keepalive}" 4 25 5 4 2 \
			"Client preshared:" 5 1 "${_client_preshared}" 5 25 5 4 2 \
			"Client group:" 6 1 "${_client_group}" 6 25 23 22 2 \
	3>&1 1>&2 2>&3)

	if [ "$?" -eq "0" ]; then
		_client_ip=$(echo "${_client_output}" | sed -n 1p)
		_client_fullname=$(echo "${_client_output}" | sed -n 3p)
		_client_keepalive=$(echo "${_client_output}" | sed -n 4p)
		_client_group=$(echo "${_client_output}" | sed -n 6p)

		client_save "${_client_ip}" "${_client_active}" "${_client_preshared}" "${_client_keepalive}" "${_client_fullname}" "${_client_group}"

		tui_infobox "Add client" "New peer was added" "2"
		return 0
	else
	        return 1
	fi
}

tui_client_edit() {
	local _client_output=""
	local _client_ip
	local _client_fullname
	local _client_keepalive
	local _client_preshared
	local _client_active
	local _client_group
	local _client_peer
	local _group_name
	local _group_desc
	local _group
	local _group_list=""
	local _status
	local _selected=1

	_client_list=$(client_list "${ETCPATH}/wg-shadmin-clients.conf")

	while [ "${_client_list}" != "" ]
	do
		_client_peer=$(echo ${_client_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
			--title "Update client" \
			--radiolist "Select one peer:" 15 60 10 \
		3>&1 1>&2 2>&3)

		_status=$(util_check_status "$?")

		if [ "${_status}" -eq "1" ]; then
			return 1
		fi

		if [ -z ${_client_peer} ]; then
			tui_infobox "Update client" "You must select a peer" "2"
		else
			_client_ip=$(grep "${_client_peer}_ip=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_active=$(grep "${_client_peer}_active=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_privkey=$(grep "${_client_peer}_privkey=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_preshared=$(grep "${_client_peer}_preshared=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_keepalive=$(grep "${_client_peer}_keepalive=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_fullname=$(grep "${_client_peer}_fullname=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_group=$(grep "${_client_peer}_group=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_selected=0
			break;
		fi
	done

	while [ ${_selected} -eq 0 ];
	do
		_client_fullname=$(${DIALOG_BIN} --title "Update client" --inputbox "Put user full name:" 10 60 "${_client_fullname}" 3>&1 1>&2 2>&3)

		if [ "$?" -eq "1" ]; then
			return 1
		fi

		if [ -n ${_group_output} ]; then
			break;
		else
			tui_infobox "Update client" "User full name can not be empty" "2"
		fi

		tui_yesno "Update client" "Do you want add Keep Alive option?"

		if [ "$?" -eq "0" ]; then
			_client_keepalive=25
		else
			_client_keepalive=0
		fi

		tui_yesno "Update client" "Do you want generate a new private key?"

		if [ "$?" -eq "0" ]; then
			_client_privkey=YES
		else
			_client_privkey=NO
		fi

		tui_yesno "Update client" "Do you want generate a preshared key?"

		if [ "$?" -eq "0" ]; then
			_client_preshared=YES
		else
			_client_preshared=NO
		fi

		tui_yesno "Add client" "Do you want activate this peer by default?"

		if [ "$?" -eq "0" ]; then
			_client_active=YES
		else
			_client_active=NO
		fi

		_group_list=$(group_list "${ETCPATH}/wg-shadmin-groups.conf")

		while [ ${_group_list} != "" ];
		do
			_client_group=$(echo ${_group_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
				--title "Update client" \
				--radiolist "Select one group (current: ${_client_group}):" 15 60 10 \
			3>&1 1>&2 2>&3)

			_status=$(util_check_status "$?")

			if [ "${_status}" -eq "1" ]; then
				return 1
			fi

			if [ -z ${_client_group} ]; then
				tui_infobox "Update client" "You must select a group" "2"
			else
				break;
			fi
		done

		_client_output=$(${DIALOG_BIN} --ok-label "Update" \
			--cancel-label "Cancel" \
			--backtitle "Wireguard administration tool" \
			--title "Update client" \
			--mixedform "Update configuration" 15 60 0 \
				"Client IP:" 1 1 "${_client_ip}" 1 25 16 15 2 \
				"Client active:" 2 1 "${_client_active}" 2 25 16 15 2 \
				"Client fullname:" 3 1 "${_client_fullname}" 3 25 23 22 0 \
				"Client keepalive:" 4 1 "${_client_keepalive}" 4 25 5 4 2 \
				"Client privkey:" 5 1 "${_client_privkey}" 5 25 5 4 2 \
				"Client preshared:" 6 1 "${_client_preshared}" 6 25 5 4 2 \
				"Client group:" 7 1 "${_client_group}" 7 25 23 22 2 \
		3>&1 1>&2 2>&3)

		if [ "$?" -eq "0" ]; then
			_client_fullname=$(echo "${_client_output}" | sed -n 3p)
			_client_keepalive=$(echo "${_client_output}" | sed -n 4p)

			client_update "${_client_peer}" "${_client_active}" "${_client_privkey}" "${_client_preshared}" "${_client_keepalive}" "${_client_fullname}" "${_client_group}"

			tui_infobox "Update client" "Peer ${_client_peer} was updated" "2"

			return 0
		else
			return 1
		fi
	done
}

tui_client_activate() {
	local _client_list
	local _client_peer
	local _peer
	local _status

	_client_list=$(client_list "${ETCPATH}/wg-shadmin-clients.conf" "0")

	while [ ${_client_list} != "" ];
	do
		_client_peer=$(echo ${_client_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
			--title "Enable/disable clients" \
			--checklist "Select one or more peers:" 15 60 10 \
		3>&1 1>&2 2>&3)

		_status=$(util_check_status "$?")

		if [ "${_status}" -eq "1" ]; then
			return 1
		fi

		util_config_set "${ETCPATH}/wg-shadmin-clients.conf" "peer.*_active" "NO"

		for _peer in $(echo ${_client_peer})
		do
			util_config_set "${ETCPATH}/wg-shadmin-clients.conf" "${_peer}_active" "YES"
		done

		tui_infobox "Enable/disable clients" "Changes were saved" "2"
	done

	return 0
}

tui_client_generate_file() {
	local _client_list
	local _client_peer
	local _client_active
	local _status
	local _selected=1

	_client_list=$(client_list "${ETCPATH}/wg-shadmin-clients.conf")

	while [ ${_client_list} != "" ];
	do
                _client_peer=$(echo ${_client_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
                                --title "Generate client file" \
                                --radiolist "Select one peer:" 15 60 10 \
                                3>&1 1>&2 2>&3)

		_status=$(util_check_status "$?")

		if [ "${_status}" -eq "1" ]; then
			return 1
		fi

                if [ -z ${_client_peer} ]; then
                        tui_infobox "Generate client file" "You must select a peer" "2"
			_selected=1
                else
			_selected=0
                fi

		if [ ${_selected} -eq 0 ]; then
			_client_active=$(grep ${_client_peer}_active= ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)

			if [ "${_client_active}" = "YES" ]; then
				client_generate_file "${_client_peer}" "${ETCPATH}/wg-shadmin-clients.conf"
				tui_infobox "Generate client file" "Configuration file of ${_client_peer} was generated" "2"
				return 0
			else
				tui_infobox "Generate client file" "Configuration file was not generated because ${_client_peer} is not enabled." "3"
				return 1
			fi
		fi
	done
}

tui_client_generate_files() {
	local _client_list
	local _client_peer
	local _client_active
	local _peer

	util_remove_config_files

	_client_list=$(grep "peer.*_ip=" "${ETCPATH}/wg-shadmin-clients.conf" | cut -d '_' -f1)

	for _peer in ${_client_list}
	do
		_client_active=$(grep ${_peer}_active= ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)

		if [ "${_client_active}" = "YES" ]; then
			client_generate_file "${_peer}" "${ETCPATH}/wg-shadmin-clients.conf"
		fi
	done

	tui_infobox "Generate client files" "Configuration files of peers-enabled were generated" "2"
	return 0
}

tui_client_generate_qrcode() {
	local _client_list
	local _client_peer
	local _client_active
	local _status
	local _selected=1

	_client_list=$(client_list "${ETCPATH}/wg-shadmin-clients.conf")

	while [ ${_client_list} != "" ];
	do
		_client_peer=$(echo ${_client_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
			--title "Generate qrcode client file" \
			--radiolist "Select one peer:" 15 60 10 \
		3>&1 1>&2 2>&3)

		_status=$(util_check_status "$?")

		if [ "${_status}" -eq "1" ]; then
			return 1
		fi

		if [ -z ${_client_peer} ]; then
			tui_infobox "Generate client file" "You must select a peer" "2"
			_selected=1
		else
			_selected=0
                fi

		if [ ${_selected} -eq 0 ]; then
			_client_active=$(grep ${_client_peer}_active= ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)

			if [ "${_client_active}" = "YES" ]; then
				client_generate_file "${_client_peer}" "${ETCPATH}/wg-shadmin-clients.conf"
				client_generate_qrcode "${ETCPATH}/peers/$(grep ${_client_peer}_group= ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)/$(grep ${_client_peer}_ip= ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2).conf"

				util_pause

				tui_infobox "Generate qrcode client file" "QRCode of ${_client_peer} was generated" "2"
				return 0
			else
				tui_infobox "Generate qrcode client file" "QRCode was not generated because ${_client_peer} is not enable." "3"
				return 1
			fi
		fi
	done
}

tui_client_view() {
	local _client_list
	local _client_peer
	local _flag
	local _status

	_client_list=$(client_list "${ETCPATH}/wg-shadmin-clients.conf")

	while [ ${_client_list} != "" ];
	do
		_client_peer=$(echo ${_client_list} | xargs ${DIALOG_BIN} --backtitle "Wireguard administration tool" \
			--title "View client file" \
			--radiolist "Select one peer:" 15 60 10 \
	        3>&1 1>&2 2>&3)

		_status=$(util_check_status "$?")

		if [ "${_status}" -eq "1" ]; then
			return 1
		else
			_client_ip=$(grep "${_client_peer}_ip=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_active=$(grep "${_client_peer}_active=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_privkey=$(grep "${_client_peer}_privkey=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_preshared=$(grep "${_client_peer}_preshared=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_keepalive=$(grep "${_client_peer}_keepalive=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_fullname=$(grep "${_client_peer}_fullname=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)
			_client_group=$(grep "${_client_peer}_group=" ${ETCPATH}/wg-shadmin-clients.conf | cut -d '"' -f2)

			if [ "${_client_preshared}" = "NO" ]; then
				_flag=2
			else
				_flag=3
			fi

			_client_output=$(${DIALOG_BIN} --ok-label "View" \
				--cancel-label "Back" \
				--insecure "$@" \
				--backtitle "Wireguard administration tool" \
				--title "View client" \
				--mixedform "Client configuration" 15 60 0 \
					"Client IP:" 1 1 "${_client_ip}" 1 25 16 15 2 \
					"Client active:" 2 1 "${_client_active}" 2 25 16 15 2 \
					"Client fullname:" 3 1 "${_client_fullname}" 3 25 23 22 2 \
					"Client keepalive:" 4 1 "${_client_keepalive}" 4 25 5 4 2 \
					"Client privkey:" 5 1 "${_client_privkey}" 5 25 23 22 3 \
					"Client preshared:" 6 1 "${_client_preshared}" 6 25 23 22 ${_flag} \
					"Client group:" 7 1 "${_client_group}" 7 25 23 22 2 \
			3>&1 1>&2 2>&3)

			if [ "$?" -eq "0" ]; then
				if [ "${_client_active}" = "YES" ]; then
					client_generate_file "${_client_peer}" "${ETCPATH}/wg-shadmin-clients.conf"
					less "${ETCPATH}/peers/$(grep ${_client_peer}_group "${ETCPATH}/wg-shadmin-clients.conf" | cut -d '"' -f2)/$(grep ${_client_peer}_ip "${ETCPATH}/wg-shadmin-clients.conf" | cut -d '"' -f2).conf"
				else
					tui_infobox "View client" "Can not view this file because ${_client_peer} is not enabled" "2"
				fi
			fi
	        fi
	done

	return 0
}

tui_yesno() {
	local _title="$1"
	local _message="$2"

	${DIALOG_BIN} --backtitle "Wireguard administration tool" --title "${_title}" --yesno "${_message}" 7 40 3>&1 1>&2 2>&3
}

tui_message() {
	local _title="$1"
	local _message="$2"

	${DIALOG_BIN} --backtitle "Wireguard administration tool" --title "${_title}" --msgbox  "${_message}" 5 50
}

tui_infobox() {
	local _title="$1"
	local _message="$2"
	local _seconds="$3"

	${DIALOG_BIN} --backtitle "Wireguard administration tool" --title "${_title}" --infobox  "${_message}" 5 50
	sleep ${_seconds}
}
